In [219]:
from itertools import product
import math
import numpy as np

In [220]:
#define the function to generate the possible outcome matrices of our game, keeping in mind the required number of 0's and 1's
def generate_matrices(n):
    matrices = []
    matrices_temp = product([0, 1], repeat = n**2)
    listed = list(matrices_temp)
    for i in range(0, len(listed)):
        if (n % 2) == 0:
            if listed[i].count(0) == ((n**2)/2):
                matrices.append(listed[i])
        else:
            if listed[i].count(0) == math.ceil((n**2)/2):
                matrices.append(listed[i])
            elif listed[i].count(1) == math.ceil((n**2)/2):
                matrices.append(listed[i])
    matrices = np.reshape(matrices, (-1, n, n))
    print("Possible outcomes:")
    print(matrices)
    print("Number of possible outcomes =", len(matrices))
    return matrices, len(matrices)

#print the possible outcome matrices of our game for n = 2
matrices, number_of_matrices = generate_matrices(2)

#define the function to separate the possible outcome matrices into zero-determinant and nonzero-determinant
def zero_det_matrices(matrices, number_of_matrices, n):
    zero_det = []
    non_zero_det = []
    for i in range(0, number_of_matrices):
        if np.linalg.det(matrices[i]) == 0:
            zero_det.append(matrices[i])
        else:
            non_zero_det.append(matrices[i])
    zero_det = np.reshape(list(zero_det), (-1, n, n))
    print()
    print("Matrices with zero determinant:")
    print(zero_det)
    non_zero_det = np.reshape(list(non_zero_det), (-1, n, n))
    print()
    print("Matrices with non-zero determinant:")
    print(non_zero_det)

#print the categorised possible outcome matrices for n = 2
zero_det_matrices(matrices, number_of_matrices, 2)

Possible outcomes:
[[[0 0]
  [1 1]]

 [[0 1]
  [0 1]]

 [[0 1]
  [1 0]]

 [[1 0]
  [0 1]]

 [[1 0]
  [1 0]]

 [[1 1]
  [0 0]]]
Number of possible outcomes = 6

Matrices with zero determinant:
[[[0 0]
  [1 1]]

 [[0 1]
  [0 1]]

 [[1 0]
  [1 0]]

 [[1 1]
  [0 0]]]

Matrices with non-zero determinant:
[[[0 1]
  [1 0]]

 [[1 0]
  [0 1]]]


In [221]:
#print the possible outcome matrices of our game for n = 3
matrices, number_of_matrices = generate_matrices(3)

#define the function to separate the possible 3 x 3 outcome matrices into zero-determinant and nonzero-determinant
zero_det_matrices(matrices, number_of_matrices, 3)

Possible outcomes:
[[[0 0 0]
  [0 0 1]
  [1 1 1]]

 [[0 0 0]
  [0 1 0]
  [1 1 1]]

 [[0 0 0]
  [0 1 1]
  [0 1 1]]

 ...

 [[1 1 1]
  [1 0 0]
  [1 0 0]]

 [[1 1 1]
  [1 0 1]
  [0 0 0]]

 [[1 1 1]
  [1 1 0]
  [0 0 0]]]
Number of possible outcomes = 252

Matrices with zero determinant:
[[[0 0 0]
  [0 0 1]
  [1 1 1]]

 [[0 0 0]
  [0 1 0]
  [1 1 1]]

 [[0 0 0]
  [0 1 1]
  [0 1 1]]

 ...

 [[1 1 1]
  [1 0 0]
  [1 0 0]]

 [[1 1 1]
  [1 0 1]
  [0 0 0]]

 [[1 1 1]
  [1 1 0]
  [0 0 0]]]

Matrices with non-zero determinant:
[[[0 0 1]
  [0 1 0]
  [1 0 1]]

 [[0 0 1]
  [0 1 0]
  [1 1 0]]

 [[0 0 1]
  [0 1 0]
  [1 1 1]]

 [[0 0 1]
  [0 1 1]
  [1 0 0]]

 [[0 0 1]
  [0 1 1]
  [1 0 1]]

 [[0 0 1]
  [0 1 1]
  [1 1 0]]

 [[0 0 1]
  [1 0 0]
  [0 1 1]]

 [[0 0 1]
  [1 0 0]
  [1 1 0]]

 [[0 0 1]
  [1 0 0]
  [1 1 1]]

 [[0 0 1]
  [1 0 1]
  [0 1 0]]

 [[0 0 1]
  [1 0 1]
  [0 1 1]]

 [[0 0 1]
  [1 0 1]
  [1 1 0]]

 [[0 0 1]
  [1 1 0]
  [0 1 0]]

 [[0 0 1]
  [1 1 0]
  [0 1 1]]

 [[0 0 1]
  [1 1 0]
  [1 0 0]]

 